---
title: "Summay of circle experiment."
author: "Jesse Leigh Patsolic"
output: 
  html_document:
    keep_md: true
---

```{r render, eval=FALSE, echo=FALSE}
require(devtools)
#devtools::install_github("mrAE/R-Rerf", ref='jtest20180426')

ref1 <- 'b6214767253220a6e67f6d239e5d46e49142a4fc' #image-patch-rectangles

devtools::install_github("mrAE/R-Rerf", ref=ref1)
require(foreach)
require(grDevices)
require(rmarkdown)
require(rerf)

rmarkdown::render("Summary.Rmd")
system('open Summary.html')
```

# Problem statment 

Consider a 100-gon where 10 vertices are colored 1 and
the rest are colored 0 according to the following rules: 

* Class 1 consists of two groups of 5 contiguous vertices colored 1.
* Class 2 consists of two groups of 6 and 4 contiguous vertices, respectively, colored 1.


### sampling

```{r}
set.seed(317)
c1 <- 500
c2 <- 500

X1 <- foreach(i = 1:c1, .combine = rbind) %do% {
  set.seed(i)
  cir <- rep(0,100)

  s1 <- sample(0:99, 1)
  l1 <- s1:(s1 + 4) %% 100

  s2 <- sample(setdiff(0:99, unique(c(l1, l1 - 4))), 1)
  l2 <- s2:(s2 + 4) %% 100

  cir[l1 + 1] <- 1
  cir[l2 + 1] <- 1

  cir
}

X2 <- foreach(i = 1:c2, .combine = rbind) %do% {
  set.seed(i)
  cir <- rep(0,100)

  s1 <- sample(0:99, 1)
  l1 <- s1:(s1 + 5) %% 100

  s2 <- sample(setdiff(0:99, unique(c(l1, l1 - 3))), 1)
  l2 <- s2:(s2 + 3) %% 100

  cir[l1 + 1] <- 1
  cir[l2 + 1] <- 1

  cir
}
```

## As an image
```{r, fig.width = 10, fig.height = 12}
X <- rbind(X1, X2)
v <- as.raster(rbind(X1, X2))
plot(v)
#par(mfrow = c(2, 2))
#v1 <- as.raster(X1)
#v2 <- as.raster(X2)
#plot(v1)
#plot(v2)
```

## As Circles

```{r, fig.width = 8, fig.height = 8}
cs <- seq(0, 2 * pi - (2 * pi / 100), length = 100)

x <- lapply(cs, sin)
y <- lapply(cs, cos)

set.seed(317)
par(mfrow = c(5,5))
for(j in sort(sample(nrow(X), 25))) {
  par(mar = c(1,1,1,1))
  plot(x, y, col = c('gray90', 'red')[X[j, ] + 1], asp = 1,
       pch = 19, xaxt='n', yaxt='n', xlab = '', ylab = '',
       cex = 0.5)
  text(0,0, label = j)
}
#dev.off()
```

## Running Randomer Forest on the Vectors

```{r}
Y  <- c(rep(0, c1), rep(1, c2))

set.seed(1030)
strain <- sort(sample(nrow(X), 750))
Xtrain <- X[strain, ]
Ytrain <- Y[strain]

stest <- setdiff(1:nrow(X), strain)
Xtest <- X[stest, ]
Ytest <- Y[stest]

p <- ncol(Xtrain)
d <- 1
iw <- 100
ih <- 1
patch.min <- 1L
patch.max <- 10L
forest <- RerF(Xtrain, Ytrain, num.cores = 1L, mat.options = list(p, d, "image-patch-rectangles", iw, ih, patch.min, patch.max), seed = 1L) 

(predictions <- Predict(Xtrain, forest, num.cores = 1L))
(error.rate <- mean(predictions != Ytrain))

(predictions <- Predict(Xtest, forest, num.cores = 1L))
(error.rate <- mean(predictions != Ytest))
```






